project: Common Ground Solutions/paso

name: default
model-methods: []
function-methods: [log,parameters,transform,traun,predict,read,write,load,save]

# Executioon
cpu_n: 12
threads_n: 24
gpu_n: 2

cv_n: 5
shuffle: 1

layer-1:
  layer-2: value



