project: Common Ground Soltions/paso
description: "Gpaso meta
kind:
  paso:
    model-methods: train,predict,checkpoint]
    function-methods: [log,parameters,transform,checkpoint]
    log-methods: train,predict,checkpoint]
    parameter-methods: train,predict,checkpoint]
    inputer-methods: train,predict,checkpoint]
    splitter-methods: train,predict,checkpoint]
    balance-methods: train,predict,checkpoint]
    augment-methods: train,predict,checkpoint]
    lerner-methods: train,predict,checkpoint]
    ploter-methods: train,predict,checkpoint]





